<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>StsConverterGui</AssemblyName>
    <RootNamespace>StsConverter.Gui</RootNamespace>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <StartupObject>StsConverter.Gui.GuiProgram</StartupObject>
    <Version>0.1.0</Version>
    <AssemblyTitle>STS Scope Converter</AssemblyTitle>
    <Product>STS Scope Converter</Product>
    <Company>DCC Studios</Company>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StsConverter\StsConverter.csproj" />
  </ItemGroup>

</Project>
